# image will be published to ghcr.io/<user>/<name>
name: Kinoite
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 40 # https://gitlab.com/fedora/ostree/ci-test

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.
  - type: rpm-ostree # install rpmfusion before rest of the packages.
    install:
       - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-40.noarch.rpm
       - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-40.noarch.rpm

  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
       - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite-multilib/repo/fedora-%OS_VERSION%/kylegospo-bazzite-multilib-fedora-%OS_VERSION%.repo?arch=x86_64
       #- https://copr.fedorainfracloud.org/coprs/ngompa/DisplayCAL/repo/fedora-%OS_VERSION%/ngompa-DisplayCAL-fedora-%OS_VERSION%.repo

    install:
       - iscsi-initiator-utils
       - kf6-kimageformats
       #- firefox
       - android-tools
       - syncthing
       - wezterm
       - zoxide
       - bat
       - eza
       - gamescope
       - mangohud
       - btop
       - fish
       - steam
       - distrobox
       - fastfetch
       #- displaycal
       - ffmpeg
       - lm_sensors
       - nvtop
       - pipewire-codec-aptx
       - yt-dlp
       - vim
       - just
       - podman-compose
       - https://github.com/ilya-zlobintsev/LACT/releases/download/v0.5.5/lact-0.5.5-0.x86_64.fedora-40.rpm
       
    remove:
       - ffmpeg-free
       - libavcodec-free
       - libavdevice-free
       - libavfilter-free
       - libavformat-free
       - libavutil-free
       - libpostproc-free
       - libswresample-free
       - libswscale-free

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
         - com.github.johnfactotum.Foliate
         - io.mpv.Mpv
         - org.keepassxc.KeePassXC
         - org.mozilla.Thunderbird
         - org.gnome.World.PikaBackup
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
